version: "3.7"
services:
  docker:
    privileged: true
    image: docker:dind
    environment: 
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - /home/hen:/home
    ports:
      - "3000:3000"

    networks:
      - jenkins

  docker-jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins-docker
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - /home/hen:/home
    ports:
      - "8080:8080"
    networks:
      - jenkins

volumes:
  jenkins-docker-certs:
  jenkins-data:

networks:
  jenkins:
    # aliases:
    #   - docker
